package Projet_Red

import "fmt"

func (p *Player) GearSlotAventure() {
	casqueEquipe := p.CheckGear("Casque en acier")
	robeEquipe := p.CheckGear("Robe magique")
	bottesEquipe := p.CheckGear("Bottes en cuir")

		if casqueEquipe && !robeEquipe && !bottesEquipe {
			fmt.Println(" ")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println("|    Casque     |   |    Torse      |   |     Pieds     |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(`|    _______    |   |               |   |               |`)
			fmt.Println("|   |  ___  |   |   |               |   |               |")
			fmt.Println(`|   | /   \ |   |   |               |   |               |`)
			fmt.Println("|   |_|   |_|   |   |               |   |               |")
			fmt.Println("|_______________|   |_______________|   |_______________|")
			fmt.Println("|Casque en acier|   |               |   |               |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(" ")
		} else if !casqueEquipe && robeEquipe && !bottesEquipe {
			fmt.Println(" ")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println("|    Casque     |   |    Torse      |   |     Pieds     |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(`|               |   |   ___/_\___   |   |               |`)
			fmt.Println("|               |   |  |         |  |   |               |")
			fmt.Println(`|               |   |  ||\     /||  |   |               |`)
			fmt.Println("|               |   |  || |-o-| ||  |   |               |")
			fmt.Println("|_______________|   |_______________|   |_______________|")
			fmt.Println("|               |   | Robe magique  |   |               |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(" ")
		} else if !casqueEquipe && !robeEquipe && bottesEquipe {
			fmt.Println(" ")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println("|    Casque     |   |    Torse      |   |     Pieds     |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(`|               |   |               |   |     _   _     |`)
			fmt.Println("|               |   |               |   |    | | | |    |")
			fmt.Println(`|               |   |               |   |  __| | | |__  |`)
			fmt.Println("|               |   |               |   | |____| |____| |")
			fmt.Println("|_______________|   |_______________|   |_______________|")
			fmt.Println("|               |   |               |   |Bottes en cuir |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(" ")
		} else if casqueEquipe && robeEquipe && !bottesEquipe {
			fmt.Println(" ")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println("|    Casque     |   |    Torse      |   |     Pieds     |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(`|    _______    |   |   ___/_\___   |   |               |`)
			fmt.Println("|   |  ___  |   |   |  |         |  |   |               |")
			fmt.Println(`|   | /   \ |   |   |  ||\     /||  |   |               |`)
			fmt.Println("|   |_|   |_|   |   |  || |-o-| ||  |   |               |")
			fmt.Println("|_______________|   |_______________|   |_______________|")
			fmt.Println("|Casque en acier|   | Robe magique  |   |               |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(" ")
		} else if !casqueEquipe && robeEquipe && bottesEquipe {
			fmt.Println(" ")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println("|    Casque     |   |    Torse      |   |     Pieds     |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(`|               |   |   ___/_\___   |   |     _   _     |`)
			fmt.Println("|               |   |  |         |  |   |    | | | |    |")
			fmt.Println(`|               |   |  ||\     /||  |   |  __| | | |__  |`)
			fmt.Println("|               |   |  || |-o-| ||  |   | |____| |____| |")
			fmt.Println("|_______________|   |_______________|   |_______________|")
			fmt.Println("|               |   | Robe magique  |   |Bottes en cuir |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(" ")
		} else if casqueEquipe && !robeEquipe && bottesEquipe {
			fmt.Println(" ")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println("|    Casque     |   |    Torse      |   |     Pieds     |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(`|    _______    |   |               |   |     _   _     |`)
			fmt.Println("|   |  ___  |   |   |               |   |    | | | |    |")
			fmt.Println(`|   | /   \ |   |   |               |   |  __| | | |__  |`)
			fmt.Println("|   |_|   |_|   |   |               |   | |____| |____| |")
			fmt.Println("|_______________|   |_______________|   |_______________|")
			fmt.Println("|Casque en acier|   |               |   |Bottes en cuir |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(" ")
		} else if casqueEquipe && robeEquipe && bottesEquipe {
			fmt.Println(" ")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println("|    Casque     |   |    Torse      |   |     Pieds     |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(`|    _______    |   |   ___/_\___   |   |     _   _     |`)
			fmt.Println("|   |  ___  |   |   |  |         |  |   |    | | | |    |")
			fmt.Println(`|   | /   \ |   |   |  ||\     /||  |   |  __| | | |__  |`)
			fmt.Println("|   |_|   |_|   |   |  || |-o-| ||  |   | |____| |____| |")
			fmt.Println("|_______________|   |_______________|   |_______________|")
			fmt.Println("|Casque en acier|   | Robe magique  |   |Bottes en cuir |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(" ")
		} else if !casqueEquipe && !robeEquipe && !bottesEquipe {
			fmt.Println(" ")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println("|    Casque     |   |    Torse      |   |     Pieds     |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(`|               |   |               |   |               |`)
			fmt.Println("|               |   |               |   |               |")
			fmt.Println(`|               |   |               |   |               |`)
			fmt.Println("|               |   |               |   |               |")
			fmt.Println("|_______________|   |_______________|   |_______________|")
			fmt.Println("|               |   |               |   |               |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(" ")
		}
		fmt.Println("--------------------------------------------------------")
		fmt.Println("             Tapez 0 pour revenir au menu               ")
		fmt.Println("________________________________________________________")
		fmt.Println("--------------------------------------------------------")
		var input string
	fmt.Scanln(&input)
	switch input {
	case "0":
		p.MenuAventure()
		return
	default: 
		fmt.Println("Tapez 0 pour revenir au menu !")
		p.GearSlotAventure()
		return
	}
}
