package Projet_Red

import "fmt"

func (p *Player) GearSlot() {
<<<<<<< HEAD
		if p.CheckItem("Casque en acier") && !p.CheckItem("Robe magique") && !p.CheckItem("Bottes en cuir") {
			fmt.Println(" ")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println("|    Casque     |   |    Torse      |   |     Pieds     |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(`|    _______    |   |               |   |               |`)
			fmt.Println("|   |  ___  |   |   |               |   |               |")
			fmt.Println(`|   | /   \ |   |   |               |   |               |`)
			fmt.Println("|   |_|   |_|   |   |               |   |               |")
			fmt.Println("|_______________|   |_______________|   |_______________|")
			fmt.Println("|Casque en acier|   |               |   |               |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(" ")

		} else if !p.CheckItem("Casque en acier") && p.CheckItem("Robe magique") && !p.CheckItem("Bottes en cuir") {
			fmt.Println(" ")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println("|    Casque     |   |    Torse      |   |     Pieds     |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(`|               |   |   ___/_\___   |   |               |`)
			fmt.Println("|               |   |  |         |  |   |               |")
			fmt.Println(`|               |   |  ||\     /||  |   |               |`)
			fmt.Println("|               |   |  || |-o-| ||  |   |               |")
			fmt.Println("|_______________|   |_______________|   |_______________|")
			fmt.Println("|               |   | Robe magique  |   |               |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(" ")
		} else if !p.CheckItem("Casque en acier") && !p.CheckItem("Robe magique") && p.CheckItem("Bottes en cuir") {
			fmt.Println(" ")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println("|    Casque     |   |    Torse      |   |     Pieds     |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(`|               |   |               |   |     _   _     |`)
			fmt.Println("|               |   |               |   |    | | | |    |")
			fmt.Println(`|               |   |               |   |  __| | | |__  |`)
			fmt.Println("|               |   |               |   | |____| |____| |")
			fmt.Println("|_______________|   |_______________|   |_______________|")
			fmt.Println("|               |   |               |   |Bottes en cuir |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(" ")
		} else if p.CheckItem("Casque en acier") && p.CheckItem("Robe magique") && !p.CheckItem("Bottes en cuir") {
			fmt.Println(" ")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println("|    Casque     |   |    Torse      |   |     Pieds     |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(`|    _______    |   |   ___/_\___   |   |               |`)
			fmt.Println("|   |  ___  |   |   |  |         |  |   |               |")
			fmt.Println(`|   | /   \ |   |   |  ||\     /||  |   |               |`)
			fmt.Println("|   |_|   |_|   |   |  || |-o-| ||  |   |               |")
			fmt.Println("|_______________|   |_______________|   |_______________|")
			fmt.Println("|Casque en acier|   | Robe magique  |   |               |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(" ")
		} else if !p.CheckItem("Casque en acier") && p.CheckItem("Robe magique") && p.CheckItem("Bottes en cuir") {
			fmt.Println(" ")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println("|    Casque     |   |    Torse      |   |     Pieds     |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(`|               |   |   ___/_\___   |   |     _   _     |`)
			fmt.Println("|               |   |  |         |  |   |    | | | |    |")
			fmt.Println(`|               |   |  ||\     /||  |   |  __| | | |__  |`)
			fmt.Println("|               |   |  || |-o-| ||  |   | |____| |____| |")
			fmt.Println("|_______________|   |_______________|   |_______________|")
			fmt.Println("|               |   | Robe magique  |   |Bottes en cuir |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(" ")
		} else if p.CheckItem("Casque en acier") && !p.CheckItem("Robe magique") && p.CheckItem("Bottes en cuir") {
			fmt.Println(" ")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println("|    Casque     |   |    Torse      |   |     Pieds     |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(`|    _______    |   |               |   |     _   _     |`)
			fmt.Println("|   |  ___  |   |   |               |   |    | | | |    |")
			fmt.Println(`|   | /   \ |   |   |               |   |  __| | | |__  |`)
			fmt.Println("|   |_|   |_|   |   |               |   | |____| |____| |")
			fmt.Println("|_______________|   |_______________|   |_______________|")
			fmt.Println("|Casque en acier|   |               |   |Bottes en cuir |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(" ")
		} else if p.CheckItem("Casque en acier") && p.CheckItem("Robe magique") && p.CheckItem("Bottes en cuir") {
			fmt.Println(" ")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println("|    Casque     |   |    Torse      |   |     Pieds     |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(`|    _______    |   |   ___/_\___   |   |     _   _     |`)
			fmt.Println("|   |  ___  |   |   |  |         |  |   |    | | | |    |")
			fmt.Println(`|   | /   \ |   |   |  ||\     /||  |   |  __| | | |__  |`)
			fmt.Println("|   |_|   |_|   |   |  || |-o-| ||  |   | |____| |____| |")
			fmt.Println("|_______________|   |_______________|   |_______________|")
			fmt.Println("|Casque en acier|   | Robe magique  |   |Bottes en cuir |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(" ")
		} else if !p.CheckItem("Casque en acier") && !p.CheckItem("Robe magique") && !p.CheckItem("Bottes en cuir") {
			fmt.Println(" ")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println("|    Casque     |   |    Torse      |   |     Pieds     |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(`|               |   |               |   |               |`)
			fmt.Println("|               |   |               |   |               |")
			fmt.Println(`|               |   |               |   |               |`)
			fmt.Println("|               |   |               |   |               |")
			fmt.Println("|_______________|   |_______________|   |_______________|")
			fmt.Println("|               |   |               |   |               |")
			fmt.Println("|===============|   |===============|   |===============|")
			fmt.Println(" ")
		}
		fmt.Println("--------------------------------------------------------")
		fmt.Println("       Tapez 0 pour revenir au menu principal        ")
		fmt.Println("________________________________________________________")
		fmt.Println("--------------------------------------------------------")
		var input string
	fmt.Scanln(&input)
	switch input {
	case "0":
		p.MainMenu()
		return
	default: 
		fmt.Println("Tapez 0 pour revenir au menu principal !")
		p.GearSlot()
		return
	}
}
=======
	fmt.Println(" ")
	fmt.Println("|===============|   |===============|   |===============|")
	fmt.Println("|    Casque     |   |    Torse      |   |     Pieds     |")
	fmt.Println("|===============|   |===============|   |===============|")
	fmt.Println(`|    _______    |   |   ___/_\___   |   |     _   _     |`)
	fmt.Println("|   |  ___  |   |   |  |         |  |   |    | | | |    |")
	fmt.Println(`|   | /   \ |   |   |  ||\     /||  |   |  __| | | |__  |`)
	fmt.Println("|   |_|   |_|   |   |  || |-o-| ||  |   | |____| |____| |")
	fmt.Println("|_______________|   |_______________|   |_______________|")
	fmt.Println("|Casque en acier|   | Robe magique  |   |Bottes en cuir |")
	fmt.Println("|===============|   |===============|   |===============|")
	fmt.Println(" ")
	if p.CheckItem("Casque en acier") && !p.CheckItem("Robe magique") && !p.CheckItem("Bottes en cuir")  {
		fmt.Println(" ")
		fmt.Println("|===============|   |===============|   |===============|")
		fmt.Println("|    Casque     |   |    Torse      |   |     Pieds     |")
		fmt.Println("|===============|   |===============|   |===============|")
		fmt.Println(`|    _______    |   |               |   |               |`)
		fmt.Println("|   |  ___  |   |   |               |   |               |")
		fmt.Println(`|   | /   \ |   |   |               |   |               |`)
		fmt.Println("|   |_|   |_|   |   |               |   |               |")
		fmt.Println("|_______________|   |_______________|   |_______________|")
		fmt.Println("|Casque en acier|   | Robe magique  |   |Bottes en cuir |")
		fmt.Println("|===============|   |===============|   |===============|")
		fmt.Println(" ")
	}else if !p.CheckItem("Casque en acier") && p.CheckItem("Robe magique") && !p.CheckItem("Bottes en cuir")  {
		fmt.Println(" ")
		fmt.Println("|===============|   |===============|   |===============|")
		fmt.Println("|    Casque     |   |    Torse      |   |     Pieds     |")
		fmt.Println("|===============|   |===============|   |===============|")
		fmt.Println(`|               |   |   ___/_\___   |   |               |`)
		fmt.Println("|               |   |  |         |  |   |               |")
		fmt.Println(`|               |   |  ||\     /||  |   |               |`)
		fmt.Println("|               |   |  || |-o-| ||  |   |               |")
		fmt.Println("|_______________|   |_______________|   |_______________|")
		fmt.Println("|Casque en acier|   | Robe magique  |   |Bottes en cuir |")
		fmt.Println("|===============|   |===============|   |===============|")
		fmt.Println(" ")
	}else if !p.CheckItem("Casque en acier") && !p.CheckItem("Robe magique") && p.CheckItem("Bottes en cuir") {
		fmt.Println(" ")
		fmt.Println("|===============|   |===============|   |===============|")
		fmt.Println("|    Casque     |   |    Torse      |   |     Pieds     |")
		fmt.Println("|===============|   |===============|   |===============|")
		fmt.Println(`|               |   |               |   |     _   _     |`)
		fmt.Println("|               |   |               |   |    | | | |    |")
		fmt.Println(`|               |   |               |   |  __| | | |__  |`)
		fmt.Println("|               |   |               |   | |____| |____| |")
		fmt.Println("|_______________|   |_______________|   |_______________|")
		fmt.Println("|Casque en acier|   | Robe magique  |   |Bottes en cuir |")
		fmt.Println("|===============|   |===============|   |===============|")
		fmt.Println(" ")
	}else if p.CheckItem("Casque en acier") && p.CheckItem("Robe magique") && !p.CheckItem("Bottes en cuir") {
		fmt.Println(" ")
	fmt.Println("|===============|   |===============|   |===============|")
	fmt.Println("|    Casque     |   |    Torse      |   |     Pieds     |")
	fmt.Println("|===============|   |===============|   |===============|")
	fmt.Println(`|    _______    |   |   ___/_\___   |   |     _   _     |`)
	fmt.Println("|   |  ___  |   |   |  |         |  |   |    | | | |    |")
	fmt.Println(`|   | /   \ |   |   |  ||\     /||  |   |  __| | | |__  |`)
	fmt.Println("|   |_|   |_|   |   |  || |-o-| ||  |   | |____| |____| |")
	fmt.Println("|_______________|   |_______________|   |_______________|")
	fmt.Println("|Casque en acier|   | Robe magique  |   |Bottes en cuir |")
	fmt.Println("|===============|   |===============|   |===============|")
	fmt.Println(" ")
	}else if p.CheckItem("Casque en acier") && p.CheckItem("Robe magique") && !p.CheckItem("Bottes en cuir") 
	}
>>>>>>> 78ef85a6cb9a6f4bf9b705147e0cc822cef08107
